### ISSUE TITLE
include and extends are blocking

### ISSUE THREAD

**Issue by mikeyhew** [jadejs/then-jade#16]
[Here is a Gist](https://gist.github.com/mikeyhew/72e69a18ff10bbea86a0) that demonstrates that include'ing templates will result to calls to fs.readFileSync during parsing.

To change this behaviour would require modifying the Parser object, which right now is "require"d directly from jade. You would also have to change the API to make the compile function asynchronous.

I just re-read the Readme for this project, and realized that avoiding blocking filesystem calls may not be the goal of this project - if that's the case, I'd recommend making that more obvious on the Readme, ie: "`then-jade` does **not** make any changes to stage 1 of this process, and in fact still uses fs.readFileSync to read template files," or however you want to say it. (Hopefully your version will be more clear than mine - I'm not much of a writer.)

**Comment by adamwong246** [comment]
+1

**Comment by jeromew** [comment]
async extends & include seem to be in the scope of jade 2+ ;

`then-jade` will not modify the compile step at this stage.

The Parser object is exported in the latest version of `then-jade` if you need to override it.

I'll add something to the readme so that it becomes clearer that only step2 becomes asynchronous.
